In [4]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input
import pandas as pd
import matplotlib.pyplot as plt


2024-07-17 16:28:53.019618: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-17 16:28:53.024817: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-17 16:28:53.112126: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-17 16:28:53.227079: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-17 16:28:53.287641: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been 

In [7]:
df = pd.read_csv("insurance_data.csv")
df['age'] = df['age']/100
df.head()

age  affordibility  bought_insurance
0  0.22              1                 0
1  0.25              0                 0
2  0.47              1                 1
3  0.52              0                 0
4  0.46              1                 1

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df[["age","affordibility"]], df.bought_insurance, test_size=0.2, random_state=41)
X_train.shape

(22, 2)

In [9]:
model = keras.Sequential([
    Dense(1, input_shape=(2,), activation="sigmoid",kernel_initializer="ones", bias_initializer="zeros")
])

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy'])
# model.fit(X_train, y_train, epochs=5000)

/home/abir/miniconda3/envs/simple_env/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2024-07-17 16:34:15.451391: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2024-07-17 16:34:15.451439: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:135] retrieving CUDA diagnostic information for host: abir-Aspire-A315-57G
2024-07-17 16:34:15.451450: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:142] hostname: abir-Aspire-A315-57G
2024-07-17 16:34:15.451695: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:166] libcuda reported version is: 535.183.1
2024-07-17 16:34:15.451773: I external/local_xla/xla/s

Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 675ms/step - accuracy: 0.5000 - loss: 0.7117
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.7109
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy

In [10]:
model.evaluate(X_test, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 275ms/step - accuracy: 1.0000 - loss: 0.3451


[0.3451061546802521, 1.0]

In [11]:
coef, intercept = model.get_weights()

In [12]:
coef, intercept

(array([[5.031614 ],
        [1.4269606]], dtype=float32),
 array([-2.9035313], dtype=float32))

### manual approach

In [13]:
import math

In [14]:
def sigmoid(x):
    return 1/(1+math.exp(-x))

In [15]:
def prediction_fucntion(age, affordibility):
    # the constants are taken from gradient descent
    result = coef[0][0]*age+coef[1][0]*affordibility+intercept[0]
    return sigmoid(result)

In [16]:
prediction_fucntion(0.47,1)

0.7085367027087004

In [17]:
prediction_fucntion(0.18,1)

0.36103373966238067

In [18]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    pred_adjusted = [val-epsilon if val==1 else val+epsilon for val in y_predicted]
    pred_adjusted = np.array(pred_adjusted)
    return -np.mean(y_true*np.log(pred_adjusted)+(1-y_true)*np.log(1-pred_adjusted))

In [19]:
def sigmoid_numpy(X):
    return 1/(1+np.exp(-X))

![gradient descent algorithm](/static/gradient_descent.png)

In [20]:
def gradient_descent(age, affordibility, y_true, epochs):
    # w1, w2, bias
    w1 = w2 = 1
    bias = 0

    rate = 0.1
    n = len(age)
    for i in range(epochs):
        # weighted sum
        weighted_sum = w1*age + w2*affordibility+bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)* np.dot(np.transpose(age),(y_predicted - y_true))
        w2d = (1/n) * np.dot(np.transpose(affordibility),(y_predicted-y_true))
        bias_d = np.mean(y_predicted-y_true)

        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d
        print(f"Epoch: {i}, {w1=}, {w2=}, {bias=}, {loss=}")
    return (w1,w2,bias)



In [21]:
# gradient_descent(X_train['age'], X_train['affordibility'],y_train, 2000)

Epoch: 0, w1=0.9949581239556605, w2=0.9896982365151494, bias=-0.02265512403649349, loss=0.7116950478185242
Epoch: 1, w1=0.9901402774083412, w2=0.9797491434106024, bias=-0.04474297925863976, loss=0.705334867159043
Epoch: 2, w1=0.9855435690273059, w2=0.9701496583700949, bias=-0.06627144946579504, loss=0.6993184529083502
Epoch: 3, w1=0.9811648804455241, w2=0.9608962313877165, bias=-0.08724894869639924, loss=0.6936316356538015
Epoch: 4, w1=0.9770008849935439, w2=0.9519848561863941, bias=-0.10768437376941423, loss=0.6882602964161111
Epoch: 5, w1=0.9730480666832142, w2=0.9434111029082707, bias=-0.12758705653757343, loss=0.6831904274609022
Epoch: 6, w1=0.969302739251126, w2=0.9351701516616743, bias=-0.14696671630212635, loss=0.6784081879760236
Epoch: 7, w1=0.9657610650862449, w2=0.9272568265332143, bias=-0.16583341280012343, loss=0.6738999544034567
Epoch: 8, w1=0.9624190738825523, w2=0.919665629702353, bias=-0.18419750013306693, loss=0.6696523653193456
Epoch: 9, w1=0.9592726808750279, w2=0.91

(5.242020140364564, 1.4831104365894678, -3.0456430384547075)

### model class

In [39]:
class myNN:
    def __init__(self, initial_w1=1, initial_w2=1, initial_bias=0):
        self.w1 = initial_w1
        self.w2 = initial_w2
        self.bias = initial_bias

    def gradient_descent(self, age, affordibility, y_true, epochs, loss_threshold):
        # w1, w2, bias
        w1,w2,bias = self.w1, self.w2, self.bias

        rate = 0.1
        n = len(age)
        for i in range(epochs):
            # weighted sum
            weighted_sum = w1*age + w2*affordibility+bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)

            w1d = (1/n)* np.dot(np.transpose(age),(y_predicted - y_true))
            w2d = (1/n) * np.dot(np.transpose(affordibility),(y_predicted-y_true))
            bias_d = np.mean(y_predicted-y_true)

            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            if i%50==0:
                print(f"Epoch: {i}, {w1=}, {w2=}, {bias=}, {loss=}")
            if loss<=loss_threshold:
                print(f"Epoch: {i}, {w1=}, {w2=}, {bias=}, {loss=}")
                break
            
        return (w1,w2,bias)
    
    def fit(self, X,y, epochs, loss_thresshold=0.4):
        (w1,w2,bias) = self.gradient_descent(X['age'],X['affordibility'],y, epochs, loss_thresshold)
        self.w1,self.w2,self.bias = w1,w2,bias

    def predict(self, X):
        weighted_sum = self.w1*X['age'] + self.w2*X['affordibility']+self.bias
        return 1/(1+np.exp(-weighted_sum))


In [40]:
my_nn = myNN()
my_nn.fit(X_train, y_train, 10000,0.4631)

Epoch: 0, w1=0.9949581239556605, w2=0.9896982365151494, bias=-0.02265512403649349, loss=0.7116950478185242
Epoch: 50, w1=0.9478275442671037, w2=0.8061364984434443, bias=-0.6398539120913885, loss=0.6065644085879566
Epoch: 100, w1=1.0599167221841261, w2=0.8733595970407256, bias=-0.8524743981180487, loss=0.5934565610255116
Epoch: 150, w1=1.1968698703029728, w2=0.9625659249920266, bias=-0.9915364877583068, loss=0.584203977482261
Epoch: 200, w1=1.3373098922958975, w2=1.0406258765214251, bias=-1.1100012743863679, loss=0.5762120154767323
Epoch: 250, w1=1.4778318688809302, w2=1.1056183664662762, bias=-1.2169287097248915, loss=0.5691155684615362
Epoch: 300, w1=1.6176070279366146, w2=1.1594236562109137, bias=-1.3149840978263931, loss=0.5626945201336783
Epoch: 350, w1=1.7562390188551842, w2=1.204028181513, bias=-1.4056768967211608, loss=0.5567988702344354
Epoch: 400, w1=1.893452080973495, w2=1.2411004329859785, bias=-1.4901420331773654, loss=0.5513245833440932
Epoch: 450, w1=2.0290353842858666, w

In [41]:
my_nn.predict(X_test)

11    0.477564
15    0.788234
10    0.352094
21    0.157722
24    0.741598
5     0.796785
dtype: float64

In [42]:
model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


array([[0.48307678],
       [0.7842854 ],
       [0.36103374],
       [0.16863787],
       [0.73870265],
       [0.7926762 ]], dtype=float32)